server:
  port: ${AUTH_PORT:9000}
  context-path: /uaa
spring:
  application:
    name: authorization-server
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost:9091,localhost:9093,localhost:9094}
  cloud:
    config:
      name: oauth2
#      uri: http://${config.server.host}:${config.server.port} has to be set exactly as -Dspring.cloud.config.uri=<value>
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      kafka:
        binder:
          zkNodes: ${ZOO_HOST:localhost}
          defaultZkPort: ${ZOO_PORT:2182}
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw    
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}/uaa/user
management:
  health:
    defaults:
      enabled: true
redirect:
  host: ${GTW_HOST:localhost}
  port: ${GTW_PORT:8080}