spring:
  application:
    name: authorization-server
server:
  port: ${port}
  context-path: /uaa
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${host}:${server.port}/uaa/user
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
  level:
    org.springframework.security: INFO
management:
  health:
    defaults:
      enabled: true        