spring:
  application:
    name: authorization-server
server:
  port: ${port}
  context-path: /uaa
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${host}:${server.port}/uaa/user
management:
  health:
    defaults:
      enabled: true        