server:
  port: ${auth.port}
  context-path: /uaa
spring:
  application:
    name: authorization-server
  kafka:
    bootstrap-servers:
      - ${kafka.host}:${kafka.port}    
  cloud:
    config:
      name: oauth2
#      uri: http://${config.server.host}:${config.server.port} has to be set exactly as -Dspring.cloud.config.uri=<value>
    bus:
      enabled: ${bus.enable:true}
    stream:
      kafka:
        binder:
          zkNodes: ${zoo.host}
          defaultZkPort: ${zoo.port}
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw    
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${auth.host}:${auth.port}/uaa/user
management:
  health:
    defaults:
      enabled: true        