server:
  port: ${port}
spring:
  application:
    name: resource
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST}:${KAFKA_PORT}
  cloud:
    config:
      name: oauth2
#      uri: http://${config.server.host}:${config.server.port} has to be set exactly as -Dspring.cloud.config.uri=<value> 
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      kafka:
        binder:
          zkNodes: ${ZOO_HOST}
          defaultZkPort: ${ZOO_PORT}
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    healthcheck:
      enabled: false 
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    instance-id: ${spring.application.name}:${random.int}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
management:
  health:
    defaults:
      enabled: true                
#management:
  #endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#        - shutdown
  #endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${AUTH_HOST}:${AUTH_PORT}/uaa/user