spring:
  application:
    name: resource
  kafka:
    bootstrap-servers:
      - ${kafka.host}:${kafka.port}    
server:
  port: ${port}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka
    healthcheck:
      enabled: false 
  instance:
    hostname: ${eureka.instance.hostname}
    instance-id: ${spring.application.name}:${random.int}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
management:
  health:
    defaults:
      enabled: true                
#management:
  #endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#        - shutdown
  #endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
security:
  user:
    password: none
  oauth2:
    resource:
      user-info-uri: http://${auth.host}:${auth.port}/uaa/user