spring:
  application:
    name: ui
server:
  port: ${port}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${eureka.instance.hostname}
    instance-id: ${spring.application.name}:${random.int}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
management:
  health:
    defaults:
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
security:
  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://${auth.host}:${auth.port}/uaa/user