spring:
  application:
    name: ui
server:
  port: ${port}
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
  level:
    org:
      springframework: INFO   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka_host}:${eureka_port}/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: ${eureka_instance_hostname}
    instance-id: ${spring.application.name}:${random.int}
#    instance-id: ${spring.application.name}:${server.port}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
management:
  health:
    defaults:
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
security:
  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://${auth_host}:${auth_port}/uaa/user