spring:
  application:
    name: ui
server:
  port: ${ui.port:8091}
logging:
  pattern:
    console: ${log.pattern:%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n}
  level:
    org:
      springframework: INFO   
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${eureka.server.uri:http://localhost:8761/eureka}
#    healthcheck:
#      enabled: true
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
security:
  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login 
    resource:
      user-info-uri: http://localhost:9000/uaa/user
      id: oauth2-resource
    client:
      access-token-uri: http://localhost:9000/uaa/oauth/token
      user-authorization-uri: http://localhost:9000/uaa/oauth/authorize
      client-id: ui_client
      client-secret: password
      scope:
      - read
      - write
#    authorization:
#      check-token-access: isAuthenticated()