spring:
  application:
    name: ui
server:
  port: ${ui.port:0}
logging:
  pattern:
    console: ${log.pattern:%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n}
  level:
    org:
      springframework: INFO   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server.uri:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
#    instance-id: ${spring.application.name}:${server.port}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
management:
  health:
    defaults:
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
security:
  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/uaa/user