server:
  port: 0
spring:
  application:
    name: order-service
  profiles:
    active:
    - dev
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost:9091,localhost:9093,localhost:9094}
  config:
    import: 
      - optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8889}
  cloud:
    config:
      name: oauth2  
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8762}/eureka
    healthcheck:
      enabled: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.int}
management:
  endpoint:
    info:
      enabled: true      
    health:
      enabled: true
    refresh:
      enabled: true
    busenv:
      enabled: true
    busrefresh:
      enabled: true  
---
spring:
  config:
    activate:
      on-profile:
      - test
  data:
    mongodb:
      uri: mongodb://userTest:password@${MONGO_HOST:localhost}:${MONGO_PORT:27018}/test
---
spring:
  config:
    activate:
      on-profile:
      - dev
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:userDev}:${MONGO_USER_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27018}/${MONGO_DB:dev}
eureka:
  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS:2}
    lease-expiration-duration-in-seconds: ${EUREKA_EVICTION_PERIOD_SECONDS:4}