server:
  port: ${PORT:0}
spring:
  application:
    name: customer-service
  profiles:
    active:
    - dev
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost:9091,localhost:9093,localhost:9094}
  config:
    import: 
      - optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8889}
  cloud:
    config:
      name: oauth2  
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
  data:
    rest:
      base-path: /api
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8762}/eureka
    healthcheck:
      enabled: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.int}
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - refresh
        - busrefresh
        - busenv
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile:
      - test
  jpa:
    database: h2
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
---    
spring:
  config:
    activate:
      on-profile:
      - dev
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DB:customer}
    username: ${MYSQL_USER:userDev}
    password: ${MYSQL_USER_PASSWORD:password}
eureka:
  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS:2}
    lease-expiration-duration-in-seconds: ${EUREKA_EVICTION_PERIOD_SECONDS:4}