server:
  port: ${port}
spring:
  application:
    name: eureka-server
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"    
eureka:
#  instance:
#    hostname: ${eureka_instance_hostname}
#    lease-expiration-duration-in-seconds: ${eureka.heartbeat.waiting.interval:1}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${host}:${server.port}/eureka/
  server:
    enable-self-preservation: false
#    expected-client-renewal-interval-seconds: ${eureka.heartbeat.sending.interval:1}
#    eviction-interval-timer-in-ms: ${eureka.eviction.job.running.ms:5000}
#    renewal-percent-threshold: ${eureka.heartbeat.expected:0.49}
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: always    