spring:
  application:
    name: log-server
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST}:${KAFKA_PORT}
  config:
    import: 
      - optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT} 
  cloud:
    config:
      name: oauth2  
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none      