spring:
  application:
    name: log-server
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost:9091,localhost:9093,localhost:9094}
  config:
    import: 
      - optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8889}
  cloud:
    config:
      name: oauth2  
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: none
          consumer:
            header-mode: none      