server:
  port: ${GTW_PORT:8080}
spring:
  application:
    name: gateway-zuul
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${KAFKA_HOSTS:localhost:9091,localhost:9093,localhost:9094}
  cloud:
    config:
      name: oauth2
#      uri: http://${config.server.host}:${config.server.port} has to be set exactly as -Dspring.cloud.config.uri=<value> 
    bus:
      enabled: ${BUS_ENABLE:true}
    stream:
      kafka:
        binder:
          zkNodes: ${ZOO_HOST:localhost}
          defaultZkPort: ${ZOO_PORT:2182}
      bindings:
        springCloudBusOutput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw
        springCloudBusInput:
          content-type: application/json
          producer:
            header-mode: raw
          consumer:
            header-mode: raw      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8762}/eureka
    healthcheck:
      enabled: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
#proxy:
#  auth:
#    routes:
#      ui: oauth2
#      webjars: passthru
zuul:
  routes:
    root:
      path: /
      service-id: ui
    webjars:
      path: /webjars/**
      service-id: ui
      strip-prefix: false
    ui:
      path: /ui/**
      service-id: ui
      sensitiveHeaders:
    resource:
      path: /resource/**
      service-id: resource
      sensitiveHeaders:
    customer:
      path: /customer/**
      service-id: customer-service
    order:
      path: /order/**
      service-id: order-service  
security:
#  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login
    resource:
      user-info-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}/uaa/user
      id: oauth2-resource
    client: 
      access-token-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}/uaa/oauth/token
      user-authorization-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}/uaa/oauth/authorize
      client-id: ui_client
      client-secret: password
      scope:
      - read
      - write
management:
  health:
    defaults:
      enabled: true
---
spring:
  profiles: dev
eureka:
  client:
    #initial-instance-info-replication-interval-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS}
    #instance-info-replication-interval-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS}
    registry-fetch-interval-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS:2}
  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_LIVE_INTERVAL_SECONDS:2}
    lease-expiration-duration-in-seconds: ${EUREKA_EVICTION_PERIOD_SECONDS:4}
ribbon:
    ServerListRefreshInterval: ${CACHE_UPDATE_INTERVAL_MS:2000}