server:
  port: ${port}
spring:
  application:
    name: gateway-zuul
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
  level:
    org:
      springframework: INFO     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka_host}:${eureka_port}/eureka
    healthcheck:
      enabled: true
  instance:
#    hostname: ${eureka_instance_hostname}
    instance-id: ${spring.application.name}:${server.port}
#    lease-renewal-interval-in-seconds: ${eureka.heartbeat.sending.interval:10}
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        - info
#  endpoint:
#    health:
#      show-details: always
#proxy:
#  auth:
#    routes:
#      ui: oauth2
#      webjars: passthru
zuul:
  routes:
    root:
      path: /
      service-id: ui
    webjars:
      path: /webjars/**
      service-id: ui
      strip-prefix: false
    ui:
      path: /ui/**
      service-id: ui
      sensitiveHeaders:
    resource:
      path: /resource/**
      service-id: resource
      sensitiveHeaders:
security:
#  sessions: stateless
  user:
    password: none
  basic:
    enabled: false
  oauth2:
    sso:
      login-path: /login
    resource:
      user-info-uri: http://${auth_host}:${auth_port}/uaa/user
#      user-info-uri: http://localhost:${port}/uaa/user      
      id: oauth2-resource
    client: 
      access-token-uri: http://${auth_host}:${auth_port}/uaa/oauth/token
#      access-token-uri: http://localhost:${port}/uaa/oauth/token
      user-authorization-uri: http://${auth_host_authorization}:${auth_port}/uaa/oauth/authorize
#      user-authorization-uri: http://localhost:${port}/uaa/oauth/authorize
      client-id: ui_client
      client-secret: password
      scope:
      - read
      - write
management:
  health:
    defaults:
      enabled: true